### ISSUE TITLE
Plugin make Problems with the server (i Tink)

### ISSUE THREAD

**Issue by MrScautHD** [Max094Reikeb/ExtraProceduresPlugin#1]

**Comment by MrScautHD** [comment]
https://mcreator.net/comment/142291

**Comment by Max094Reikeb** [comment]
Could you provide crash report here please?

**Comment by MrScautHD** [comment]
https://pastebin.com/s57yFiDy i have no idea but i have added you plugin and now is not working the server

**Comment by MrScautHD** [comment]
the link is the crash report :) https://pastebin.com/s57yFiDy

**Comment by Max094Reikeb** [comment]
Could you tell me what version of MCreator you used with the plugin, and what element of the plugin did you use?

**Comment by MrScautHD** [comment]
the newst Snapchot and the Get item form slot 0 of block...

**Comment by MrScautHD** [comment]
but in Mcreator is the server work

**Comment by Max094Reikeb** [comment]
This plugin hasn't been tested for MCreator 2020.4. Considering the new snapshot can have bugs the final release won't probably have, I'm advising you to stay in 2020.3. On the MCreator topic of the plugin, it's specified that the plugin only works for MCreator 2020.3 for the moment.

**Comment by MrScautHD** [comment]
oh ok :(

**Comment by Max094Reikeb** [comment]
MrScautHD, is your bug still happening with MCreator 2020.4 (final release)?

**Comment by MrScautHD** [comment]
yes in final Release is it now fixed :)
